### ISSUE TITLE
Django: generovanie diplomov

### ISSUE THREAD

**Issue by pavelpetrovic** [TIS2023-FMFI/robocup#14]
priklad
[Diplom Erebus - 1.miesto.docx](https://github.com/TIS2023-FMFI/robocup/files/13163281/Diplom.Erebus.-.1.miesto.docx)

**Comment by FiiL123** [comment]
https://pythonguides.com/convert-html-page-to-pdf-using-django/

**Comment by FiiL123** [comment]
urobil som barebones verziu, kde sa vypisuju data z databazy do pdf pre kazdu kategoriu. treba dorobit styly @Oliver00000000 .

**Comment by pavelpetrovic** [comment]
v githube? mam to vypullovat? ci uz ste to aj?
(uz nam bezia registracie...)

potom bola este ta otazka, ci tam vypnut tie debugove vypisy nejak, ked sa
nieco niekde nepodari, tak to hodi to debugovacie okno aj so zdrojakom...

p

**Comment by FiiL123** [comment]
[diplomy]
Je to v inej branchi a k registrácii irelevantné. Navyše ten template je momentálne len plain text.. 
[debug]
Čo sa týka tohoto, idem sa na to pozrieť a ak to bude v pohode tak rovno zmením na serveri.

**Comment by FiiL123** [comment]
@pavelpetrovic nebugovacie vypisy som vypol uz na serveri.

**Comment by FiiL123** [comment]
template doplni organizator
