### ISSUE TITLE
Katalóg požiadaviek

### ISSUE THREAD

**Issue by Oliver00000000** [TIS2023-FMFI/robocup#2]
Je potrebné vytvoriť katalóg požiadaviek a pojmy z katalógu, ktoré treba opísať alebo vysvetliť treba definovať v Slovníku pojmov.

**Comment by Oliver00000000** [comment]
Spísali sme prvú verziu katalógu požiadaviek.

**Comment by pavelpetrovic** [comment]
nove informacie:

- kategoria Soccer aktualne system Mareka Suppu, ale bolo by velmi vhodne to nahradit
- priorita kriterii pri hodnoteni futbalu:
    1. pocet bodov (3, 1, 0 - vyhra, remiza, prehra)
    2. rozdiel skore
    3. vzajomny zapas
   (ak by sa nahodou dali prehodit 2,3 v pripade potreby, potesilo by)

editujeme: https://docs.google.com/document/d/1OZVce9BUIlvx0gI-GMqGzc9HFmX0h_6nRkrCE-vz-08/edit?usp=sharing

**Comment by FiiL123** [comment]
Doeditoval som poziadavky, ktore sme vykomunikovali na posledom stretnuti. Prosim grammar a form edity.

**Comment by mbuchalova** [comment]
Skontrolovala som gramatiku. Doplnila a upravila som text podľa návrhov. Prosím o kontrolu doplnených vecí.

**Comment by FiiL123** [comment]
done
