### ISSUE TITLE
Byro: Z našich stretnutí

### ISSUE THREAD

**Issue by pavelpetrovic** [TIS2023-FMFI/robocup#3]
Sem budem kopírovať moje krátke poznámky z našich stretnutí:

11.10.

pritomni: vsetci
potrebujeme rozhybat projekt, zatial nam issues nefungovali
mame cvicny repozitar, hura, ale hanoi este treba opravit
pridali sme zvysnych dvoch clenov do timu
mam uz aj prvu zapisnicu ale prosim, vzdy vsetci pritomni
pozrel som si prvy navrh KP, hura, vesele smeruje k cielu, ked bude novsia verzia poslat.
v 2. casti plynuly zrozumitelny text, v 3. casti jednotlive separovane myslienky formou poziadaviek.

**Comment by mbuchalova** [comment]
Zápisnica zo stretnutia z 11.10.2023 je spísaná

**Comment by pavelpetrovic** [comment]
18.10.
--
pritomni vsetci
zatial v projekte iba KP, issues treba rozprudit
primary/secondary sa nahradza ZS/SS
mame aj zapisnicu
presli sme co ma byt v navrhu
co najksor dotiahnut KP do vyslednej podoby a notifikovat ma cez teams

**Comment by pavelpetrovic** [comment]
25.10.
--
vsetci pritomni
issues - prosim nastavit granularitu vhodne
inak issues vyzeraju slubne
pekna zapisnica
akutalizuje sa KP, uz konvergujeme
 
1.11. sviatok
 
8.11.
chyba Filip K
KP je cerstvo nova verzia, ktoru snad uz iba schvalime dnes
navrh UI sa vyvija, niektore casti su na pozretie
tim sa venoval studiu technologie
zapisnica existuje, potrebujem aby boli ulohy rozdelene
pozreli sme UI a pokusime sa dohodnut stretnutie s oboma zvysnymi idealne o tyzden takto na finalne potvrdenie
mame skoro finalnu verziu KP, par uprav nasleduje
 
15.11.
Filip nas opustil
upravovali sme KP do finalnej podoby
nabuduce prosim uz vytvorit zaklad dokumentu navrh
 
22.11.
vsetci pritomni
prosim aktualizovat KP a dopisat pozadovane upravy pod navrh UI
prosim stavovy alebo sekvencny diagram do navrhu
a vytvorit dokument navrh, kde sa daju veci pridat
plan implementacie

**Comment by pavelpetrovic** [comment]
zostava (prosim do 1.marca):

- vysledkove listiny podla vekovych kategorii  
 - nahravanie PDF vysledkovych listin  (organizator+) a ich download (verejne)
 - check-in - upravy registrovanych  
 - diplomy si vyrobime sami
 - doupratovat issues v projekte, branches v kode
