### ISSUE TITLE
Django: check-in funkcionalita

### ISSUE THREAD

**Issue by FiiL123** [TIS2023-FMFI/robocup#32]
Vyhladavanie registratora napr. podla emailu, mena timu organizacie a podobne

**Comment by FiiL123** [comment]
funkcionalina vyhladavania a ukladania stavu checkinu urobena.
podla mna treba este nasledujuce veci: 
- [x] registrovanie/uprava timov a osob pod registratorom
- [x] krajsi vizual

**Comment by Oliver00000000** [comment]
Done
