### ISSUE TITLE
Django: pridat messages

### ISSUE THREAD

**Issue by FiiL123** [TIS2023-FMFI/robocup#36]
Django ma message framework:
https://docs.djangoproject.com/en/5.0/ref/contrib/messages/

Pri veciach ako vytvarani ludi, editovani, check-ine a podobne by bolo pekne implementovat, take to, ze ti niekde v rohu vybehne, ze bolo ulozene..

**Comment by FiiL123** [comment]
pridane do templatu v [0de9515](https://github.com/TIS2023-FMFI/robocup/commit/0de951528fee1a79452e02ad59572c27e9ed2172) 
a nejake success pridane spravy pridane v [2742437](https://github.com/TIS2023-FMFI/robocup/commit/2742437dd2f44881a8fd503e33da94ff4638afe0)

Treba na to mysliet pri dalsich veciach.

**Comment by Oliver00000000** [comment]
Filip finished it
