### ISSUE TITLE
linka na vygenerovanie hesla

### ISSUE THREAD

**Issue by pavelpetrovic** [TIS2023-FMFI/robocup#41]
Katalog poziadaviek 3.1.5:

Prihlasovanie do účtov administrátora, organizátora a vedúceho výpravy
Registrovaní používatelia sa do systému prihlasujú mailom a heslom, ktoré zadali pri vytváraní
účtu, **formulár dovolí poslať link na znovu vytvorenie hesla k už existujúcemu účtu.**

**Comment by FiiL123** [comment]
done
