### ISSUE TITLE
Incorrect numbering in results

### ISSUE THREAD

**Issue by pavelpetrovic** [TIS2023-FMFI/robocup#60]
The numbers in the resulting list of teams are wrong.
This needs to be fixed ASAP, because these are official public results and they are shown wrong.
Please fix now.

**Comment by FiiL123** [comment]
Fixed in 8ce6b31. 
![image](https://github.com/TIS2023-FMFI/robocup/assets/15289967/25225c85-a52e-43e4-9ef4-e65b94f5352a)

**Comment by pavelpetrovic** [comment]
este v tej robotickej ruke su dve prve miesta zs, v celkovom sa tak zobrazuju ale v zs je to ako 1, 2

**Comment by FiiL123** [comment]
v robotickej ruke su zadane tieto vysledky:
[
    {
        "nazov": "XLC–Nemo",
        "poradie": "1",
        "body": "85"
    },
    {
        "nazov": "Ulany",
        "poradie": "1",
        "body": "85"
    },
    {
        "nazov": "Robko",
        "poradie": "3",
        "body": "60"
    }
]

teda to je ako delene prve mieste.. v tom zobrazeni, kde si vsetci sa berie `poradie` z tohoto jsonu

**Comment by pavelpetrovic** [comment]
ved, ale v zs je to uz ako 1, 2 a aj tam ma byt 1, 1.
