### ISSUE TITLE
Oboznámenie sa s moqups

### ISSUE THREAD

**Issue by mbuchalova** [TIS2023-FMFI/robocup#8]
Oboznámenie sa s moqups, kvôli vytvoreniu návrhu.

**Comment by Oliver00000000** [comment]
https://app.moqups.com/ly3oG515GgHWgwDA8yyknUYQcTcQThw3/view/page/ad64222d5

**Comment by FiiL123** [comment]
presli sme na inu aplikaciu vid #7
